workflows:
  android-cctv-debug:
    name: CCTV Investigator Debug APK
    max_build_duration: 20
    environment:
      java: 17
    scripts:
      - name: Install Gradle
        script: |
          brew install gradle
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
