workflows:
  android-cctv-debug:
    name: CCTV Investigator Debug APK
    max_build_duration: 20
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
